version: 0.2

phases:
  install:
    commands:
      - npm ci
  build:
    commands:
      - npm run build

artifacts:
  files:
  - "out/**/*"
  - "api/**/*"
  - "cdk/**/*"

cache:
  paths:
    - "./node_modules/**/*"
    - ".next/**/*"
